model_name: xdxd_spacenet4

model_path: '/path_to_baseline/models/sn7_baseline/xdxd_final.pth'
train: false
infer: true

pretrained: true
nn_framework: torch
batch_size: 6

data_specs:
  width: 512
  height: 512
  dtype:
  image_type: zscore
  rescale: false
  rescale_minima: auto
  rescale_maxima: auto
  channels: 4
  label_type: mask
  is_categorical: false
  mask_channels: 1
  val_holdout_frac: 0.1
  data_workers:

training_data_csv:
validation_data_csv:
inference_data_csv: '/local_data/sn7/aws_download/csvs/sn7_baseline_test_public_df.csv'

training_augmentation:
  augmentations:
    DropChannel:
      idx: 3
      axis: 2
    HorizontalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    RandomCrop:
      height: 512
      width: 512
      p: 1.0
  p: 1.0
  shuffle: true
validation_augmentation:
  augmentations:
    DropChannel:
      idx: 3
      axis: 2
    CenterCrop:
      height: 512
      width: 512
      p: 1.0
  p: 1.0
inference_augmentation:
  augmentations:
    DropChannel:
      idx: 3
      axis: 2
      p: 1.0
  p: 1.0
training:
  epochs: 300
  steps_per_epoch:
  optimizer: Adam
  lr: 1e-4
  opt_args:
  loss:
    bcewithlogits:
    jaccard:
  loss_weights:
    bcewithlogits: 10
    jaccard: 2.5
  metrics:
    training:
    validation:
  checkpoint_frequency: 10
  callbacks:
    early_stopping:
        patience: 24
    model_checkpoint:
      filepath:
      monitor: val_loss
    lr_schedule:
      schedule_type: arbitrary
      schedule_dict:
        milestones:
          - 200
        gamma: 0.1
  model_dest_path:
  verbose: true

inference:
  window_step_size_x:
  window_step_size_y:
  output_dir: '/path_to_baseline/inference_out/sn7_baseline_preds/raw'